name: Generate python distributions
on:
  push:
    branches:
      - 1-github-actions
    tags:
      - v*

jobs:
  build:
    name: Build distribution
    runs-on: ${{ matrix.os_dist.os }}
    strategy:
      matrix:
        os_dist: [
          {os: ubuntu-latest, dist: cp36-manylinux_x86_64},
          {os: ubuntu-latest, dist: cp37-manylinux_x86_64},
          {os: ubuntu-latest, dist: cp38-manylinux_x86_64},
          {os: ubuntu-latest, dist: cp39-manylinux_x86_64},
          {os: ubuntu-latest, dist: cp310-manylinux_x86_64},
          {os: ubuntu-latest, dist: cp311-manylinux_x86_64},
          {os: ubuntu-latest, dist: cp312-manylinux_x86_64},

          {os: ubuntu-latest, dist: cp36-manylinux_i686},
          {os: ubuntu-latest, dist: cp37-manylinux_i686},
          {os: ubuntu-latest, dist: cp38-manylinux_i686},
          {os: ubuntu-latest, dist: cp39-manylinux_i686},
          {os: ubuntu-latest, dist: cp310-manylinux_i686},
          {os: ubuntu-latest, dist: cp311-manylinux_i686},
          {os: ubuntu-latest, dist: cp312-manylinux_i686},

          {os: ubuntu-latest, dist: cp36-musllinux_x86_64},
          {os: ubuntu-latest, dist: cp37-musllinux_x86_64},
          {os: ubuntu-latest, dist: cp38-musllinux_x86_64},
          {os: ubuntu-latest, dist: cp39-musllinux_x86_64},
          {os: ubuntu-latest, dist: cp310-musllinux_x86_64},
          {os: ubuntu-latest, dist: cp311-musllinux_x86_64},
          {os: ubuntu-latest, dist: cp312-musllinux_x86_64},

          {os: ubuntu-latest, dist: cp36-musllinux_i686},
          {os: ubuntu-latest, dist: cp37-musllinux_i686},
          {os: ubuntu-latest, dist: cp38-musllinux_i686},
          {os: ubuntu-latest, dist: cp39-musllinux_i686},
          {os: ubuntu-latest, dist: cp310-musllinux_i686},
          {os: ubuntu-latest, dist: cp311-musllinux_i686},
          {os: ubuntu-latest, dist: cp312-musllinux_i686},

          {os: macos-latest, dist: cp36-macosx_x86_64, macosarch: x86_64},
          {os: macos-latest, dist: cp37-macosx_x86_64, macosarch: x86_64},
          {os: macos-latest, dist: cp38-macosx_x86_64, macosarch: x86_64},
          {os: macos-latest, dist: cp39-macosx_x86_64, macosarch: x86_64},
          {os: macos-latest, dist: cp310-macosx_x86_64, macosarch: x86_64},
          {os: macos-latest, dist: cp311-macosx_x86_64, macosarch: x86_64},
          {os: macos-latest, dist: cp312-macosx_x86_64, macosarch: x86_64},

          {os: macos-latest, dist: cp38-macosx_arm64, macosarch: arm64},
          {os: macos-latest, dist: cp39-macosx_arm64, macosarch: arm64},
          {os: macos-latest, dist: cp310-macosx_arm64, macosarch: arm64},
          {os: macos-latest, dist: cp311-macosx_arm64, macosarch: arm64},
          {os: macos-latest, dist: cp312-macosx_arm64, macosarch: arm64},

          {os: windows-2019, dist: cp36-win_amd64},
          {os: windows-2019, dist: cp37-win_amd64},
          {os: windows-2019, dist: cp38-win_amd64},
          {os: windows-2019, dist: cp39-win_amd64},
          {os: windows-2019, dist: cp310-win_amd64},
          {os: windows-2019, dist: cp311-win_amd64},
          {os: windows-2019, dist: cp312-win_amd64},

          {os: windows-2019, dist: cp36-win_win32},
          {os: windows-2019, dist: cp37-win_win32},
          {os: windows-2019, dist: cp38-win_win32},
          {os: windows-2019, dist: cp39-win_win32},
          {os: windows-2019, dist: cp310-win_win32},
          {os: windows-2019, dist: cp311-win_win32},
          {os: windows-2019, dist: cp312-win_win32},
        ]
    env:
      CIBW_BUILD: "${{ matrix.os_dist.dist }}"
      CIBW_ARCHS_MACOS: "${{ matrix.os_dist.macosarch }}"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v3

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.16.5

    - name: Build wheels
      run: python -m cibuildwheel --output-dir dist

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os_dist.os }}--${{ matrix.os_dist.dist }}--${{ strategy.job-index }}
        path: ./dist/*.whl
